image: docker:latest

variables:
  DOCKER_DRIVER: overlay
  # You must set the pip cache directory to be inside project dir since we can only
  # cache local items.
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - build

services:
  - docker:dind

cache:
  key: ${CI_PROJECT_NAME}
  paths:
    - .cache/pip

before_script:
  - docker info
  - apk update
  - apk upgrade
  - apk add curl jq python3 python3-dev build-base libffi-dev libressl-dev gettext
  - curl -O https://bootstrap.pypa.io/get-pip.py
  - python3 get-pip.py
  # Install python docker image, this cache is shared for the repo
  - pip install docker-compose

build:
  stage: build
  script:
    # Because we are using slashes to denote the namesapce, we need to change the sed seperator
    - sed -i "s~%%REGISTRY_PATH%%~$CI_REGISTRY_IMAGE/${CI_COMMIT_REF_NAME}~"  docker-compose.feature.yml
    - cat docker-compose.feature.yml
    - docker-compose -f docker-compose.yml -f docker-compose.feature.yml build
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker-compose -f docker-compose.yml -f docker-compose.feature.yml push
