image: docker:latest

variables:
  DOCKER_DRIVER: overlay

stages:
  - build

services:
  - docker:dind

before_script:
  - docker info
  - apk update
  - apk upgrade
  - apk add curl jq python3 python3-dev build-base libffi-dev libressl-dev gettext
  - curl -O https://bootstrap.pypa.io/get-pip.py
  - python3 get-pip.py
  - pip install docker-compose

build:
  stage: build
  script:
    - docker-compose -f docker-compose.test.yml build
