version: "3.7"

services:
  scraper:
    image: "%%REGISTRY_PATH%%/scraper:%%TAG_APPEND%%"
  deploy:
    restart_policy:
      condition: no

  frontend:
    image: "%%REGISTRY_PATH%%/frontend:%%TAG_APPEND%%"
    ports:
      - 5001:5000
