version: "3.7"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    entrypoint: ["npm", "run", "dev"]
    environment:
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: 5000
    ports:
      - 5000:5000

  scraper:
    build:
      context: .
      dockerfile: scraper.Dockerfile
    command: ["spiders.py", "--help"]
    volumes:
      - ./scrapy.cfg:/app/scrapy.cfg
      - ./scraper:/app/scraper
      - ./spiders.py:/app/spiders.py
    depends_on:
      - "mongo"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
