version: "3.7"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    entrypoint: ["npm", "run"]
    command: ["start"]
    environment:
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: 5000
    ports:
      - 5000:5000

  scraper:
    build:
      context: .
      dockerfile: scraper.Dockerfile
    command: ["crawl.py", "--help"]
