version: "3.7"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    entrypoint: ["npm", "run", "dev"]
    environment:
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: 5000
    ports:
      - 5000:5000

  scraper:
    build:
      context: .
      dockerfile: scraper.Dockerfile
    command: ["crawl.py", "--help"]
    volumes:
      - ./scrapy.cfg:/app/scrapy.cfg
      - ./scraper:/app/scraper
      - ./crawls:/app/crawls
      - ./crawl.py:/app/crawl.py
